export type Path =
  | 'form'
  | 'message'
  | 'speaker'
  | 'speaker_cfp'
  | 'speaker_information'
  | 'volunteer'
  | 'store'
  | 'store_preorder'
  | 'store_samedaysales'
  | 'sponsor'
  | 'code-of-conduct'
  | 'privacy'
  | 'team'
