name: 'Install packages'

description: 'Install bun and dependencies'

runs:
  using: 'composite'
  steps:
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - uses: oven-sh/setup-bun@v1
      name: Install bun
      id: bun-install
      with:
        bun-version: 1.0.25

    - name: Install dependencies
      run: bun install
      shell: bash
