name: After Purchase CI

on:
  # 6 時間おきに実行
  schedule:
    - cron: 0 1/2 * * * # https://crontab.guru/#0_1/6_*_*_*
  # push:
  #   branches:
  #     - main
  pull_request:
    branches:
      - main

jobs:
  after-purchase:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.17.0]

    steps:
      - uses: actions/checkout@v4

      - name: Install packages
        uses: ./.github/actions/install-packages

      - name: Build after purchase
        run: bun build-after-purchase
        working-directory: apps/peatix-adapter
        env:
          PEATIX_EVENT_ID: ${{ secrets.PEATIX_EVENT_ID }}
          PEATIX_BASIC_EMAIL: ${{ secrets.PEATIX_BASIC_EMAIL }}
          PEATIX_BASIC_PASSWORD: ${{ secrets.PEATIX_BASIC_PASSWORD }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
