name: Chromatic CI

on: push

jobs:
  chromatic:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.19.0]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install packages
        uses: ./.github/actions/install-packages
      - name: Run Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          workingDir: ./packages/ui
          storybookBaseDir: ./packages/ui
          untraced: \"./packages/!(ui)/**\"
          exitZeroOnChanges: true
          onlyChanged: true
        env:
          LOG_LEVEL: 'debug'
