name: Chromatic

on: workflow_call

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-chromatic
  cancel-in-progress: true

permissions:
  actions: write
  contents: read

jobs:
  chromatic:
    name: Chromatic
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.19.0]

    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install packages
        uses: ./.github/actions/install-packages
      - name: Run Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          workingDir: ./packages/ui
          exitZeroOnChanges: true
          exitOnceUploaded: true
          onlyChanged: true
          skip: '@(renovate/**|dependabot/**)'
        env:
          LOG_LEVEL: 'debug'
