name: Chromatic CI

on: push

jobs:
  chromatic:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.19.0]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: git fetch origin ${{ github.base_ref }} --depth=1

      - id: diff
        run: echo "::set-output name=changed::$(git diff --name-only origin/${{ github.base_ref }} HEAD --relative ./packages/ui/ | wc -l)"

      - name: Install packages
        uses: ./.github/actions/install-packages
      - name: Run Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          workingDir: packages/ui
          exitZeroOnChanges: true
          onlyChanged: true
          diagnostics: true
          storybookBaseDir: ./packages/ui
        env:
          LOG_LEVEL: 'debug'
