name: Node.js CI

on:
  # push:
  #   branches:
  #     - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.11.1]

    steps:
      - uses: actions/checkout@v4

      - name: Install packages
        uses: ./.github/actions/install-packages

      - name: Lint check
        run: bun lint

  unit-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.11.1]

    steps:
      - uses: actions/checkout@v4

      - name: Install packages
        uses: ./.github/actions/install-packages

      - name: Unit test
        run: bun vitest

  typecheck:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.11.1]

    steps:
      - uses: actions/checkout@v4

      - name: Install packages
        uses: ./.github/actions/install-packages

      - name: Type check
        run: bun typecheck
        working-directory: apps/web