name: Node.js CI

on:
  # push:
  #   branches:
  #     - main
  pull_request:
    branches:
      - main

jobs:
  diff:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.19.0]

    steps:
      - uses: actions/checkout@v4

      - name: Install packages
        uses: ./.github/actions/install-packages

      - name: Check diffs
        uses: ./.github/actions/check-diffs

  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.19.0]

    steps:
      - uses: actions/checkout@v4

      - name: Install packages
        uses: ./.github/actions/install-packages

      - name: Lint check
        run: bun lint

  unit-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.19.0]

    steps:
      - uses: actions/checkout@v4

      - name: Install packages
        uses: ./.github/actions/install-packages

      - name: Unit test
        run: bun vitest

  # e2e-test:
  #   runs-on: ubuntu-latest

  #   strategy:
  #     matrix:
  #       node-version: [18.19.0]

  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Install packages
  #       uses: ./.github/actions/install-packages

  #     - name: E2E test
  #       run: bun cypress:ci
  #       working-directory: apps/web

  typecheck:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.19.0]

    steps:
      - uses: actions/checkout@v4

      - name: Install packages
        uses: ./.github/actions/install-packages

      - name: Type check
        run: bun typecheck
        working-directory: apps/web